### PR TITLE
cgroups/systemd: add cgroup-v2 path to the list when using hybrid mode

### PR DESCRIPTION
**Pull request by mauriciovasquezbernal**
Currently, the parent process of the container is moved to the right
cgroup-v2 tree when systemd is using a hybrid model (last line with 0::):

$ runc --systemd-cgroup run myid
/ # cat /proc/self/cgroup
12:cpuset:/system.slice/runc-myid.scope
11:blkio:/system.slice/runc-myid.scope
10:devices:/system.slice/runc-myid.scope
9:hugetlb:/system.slice/runc-myid.scope
8:memory:/system.slice/runc-myid.scope
7:rdma:/
6:perf_event:/system.slice/runc-myid.scope
5:net_cls,net_prio:/system.slice/runc-myid.scope
4:freezer:/system.slice/runc-myid.scope
3:pids:/system.slice/runc-myid.scope
2:cpu,cpuacct:/system.slice/runc-myid.scope
1:name=systemd:/system.slice/runc-myid.scope
0::/system.slice/runc-myid.scope

However, if a second process is executed in the same container, it is
not moved to the right cgroup-v2 tree:

$ runc exec myid /bin/sh -c 'cat /proc/self/cgroup'
12:cpuset:/system.slice/runc-myid.scope
11:blkio:/system.slice/runc-myid.scope
10:devices:/system.slice/runc-myid.scope
9:hugetlb:/system.slice/runc-myid.scope
8:memory:/system.slice/runc-myid.scope
7:rdma:/
6:perf_event:/system.slice/runc-myid.scope
5:net_cls,net_prio:/system.slice/runc-myid.scope
4:freezer:/system.slice/runc-myid.scope
3:pids:/system.slice/runc-myid.scope
2:cpu,cpuacct:/system.slice/runc-myid.scope
1:name=systemd:/system.slice/runc-myid.scope
0::/user.slice/user-1000.slice/session-8.scope

This commit makes that processes executed with exec are placed into the
right cgroup-v2 tree.  The implementation checks if systemd is using a
hybrid mode (by checking if cgroups-v2 is mounted in
/sys/fs/cgroup/unified), if yes, the path of the cgroup-v2 slice for
this container is saved into the cgroup path list.

### CODE REVIEW

**Comment by alban** [comment]
I would add a word about the use case in the commitmsg, such as:

> Having the processes of the container in its own cgroup-v2 is useful for any BPF programs that rely on [bpf_get_current_cgroup_id()](https://github.com/torvalds/linux/commit/bf6fa2c893c5237b48569a13fa3c673041430b6c). We need this for [Inspektor Gadget](https://github.com/kinvolk/inspektor-gadget).

**Comment by alban** [comment]
It looks good to me to do a PR upstream :+1:

**Comment by mauriciovasquezbernal** [comment]
Closing this one as it was intended to gather feedback instead of actually being merged.

**Comment by invidian** [comment]
Should we put here the reference to upstream PR?

Also, @mauriciovasquezbernal can this PR branch be removed? Upstream PR seems to be opened from another branch.

**Comment by mauriciovasquezbernal** [comment]
For sure: this is the upstream PR https://github.com/opencontainers/runc/pull/2087.
I also deleted the branch of this PR.

**Pull request closed without merging**
